en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "SMaHT Family Donor Program."
  title: "SMaHT Family Donor Program"
  params:
    description: "SMaHT Family Donor Program"
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Contact Us"
      link: "/contact-us/"
    footer_cta:
      text: "Contact Us"
      link: "/contact-us/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "#"
      weight: 1
    - identifier: "understanding-somatic-mosaicism"
      name: "Understanding Somatic Mosaicism"
      url: "/understanding-somatic-mosaicism/"
      weight: 1
      # post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    - identifier: "resources"
      name: "Resources"
      url: "/resources/"
      weight: 2
      # post: "Nulla consequat massa quis enim. Donec pede justo."
      parent: "about"
    # - identifier: "child-2"
    #   name: "Example Child Page"
    #   url: "/example-page/"
    #   weight: 2
    #   post: "Aenean commodo ligula get dolor. Aenean massa."
    #   parent: "about"
    # - identifier: "child-3"
    #   name: "Example External page"
    #   url: "https://cncf.io?ref=dot-org"
    #   weight: 3
    #   post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
    #   parent: "about"
    - identifier: "our-purpose"
      name: "Our Purpose"
      url: "/our-purpose/"
      weight: 2
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 4
    - identifier: "team"
      name: "Team"
      url: "#"
      weight: 3
    - identifier: "ethics-team"
      name: "Ethics Team"
      url: "/ethics-team/"
      weight: 1
      parent: "team"
    - identifier: "scientific-research-team"
      name: "Scientific Research Team"
      url: "/scientific-research-team/"
      weight: 2
      parent: "team"
    # - identifier: "example"
    #   name: "External"
    #   url: "https://cncf.io?ref=dot-org"
    #   weight: 5
# es:
#   languageName: Spanish
#   contentDir: content/es
#   weight: 2
#   title: "Título del Sitio"
#   params:
#     description: "Descripción del Sitio"
#   menu:
#     main:
#     - identifier: "about"
#       name: "Acerca de"
#       url: "/example-page/"
#       weight: 1
#     - identifier: "child-1"
#       name: "Página Hija de Ejemplo"
#       url: "/example-page/"
#       weight: 1
#       parent: "about"
#     - identifier: "faq"
#       name: "FAQs"
#       url: "/faq/"
#       weight: 3
#     - identifier: "blog"
      # name: "Blog"
      # url: "/blog/"
      # weight: 2
